/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DibujoDA.java
 *
 * Created on 08-oct-2011, 15:29:21
 */
package gui.ventanas;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Arturo
 */
public class DibujoDA extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BufferedImage image;

    boolean mouseAdentro = false;
    public int posX = 0;
    public int posY = 0;
    
    public int avanceX = 3;
    public int avanceY = 3;

    public int toleranciaX = 100;
    public int toleranciaY = 50;
    
    /** Creates new form DibujoDA */
    public DibujoDA() {
        this.initComponents();
    }

    public void SetImage(String nombreImagen)
    {
        try {                
          image = ImageIO.read(new File(nombreImagen));

       } catch (IOException ex) {
            ex.printStackTrace();
       }
        

    }
    @Override
    public void paintComponent(Graphics g) {
        
        g.drawImage(image, posX, posY, null); // see javadoc for more info on the parameters
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.mouseAdentro = true;
       // System.out.println("Entro mouse");
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.mouseAdentro = false;
        //System.out.println("Salio mouse");
    }//GEN-LAST:event_formMouseExited

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        if (image == null) return;
        if (!mouseAdentro) return;
        //muy a la derecha
        //System.out.println("Dibujando en " + posX + ";" + posY);
        //System.out.println("Mouse en " + evt.getX() + ";" + getWidth());
        if (evt.getX() + toleranciaX < getWidth())
            posX+=avanceX;
        
        //muy a la izquierda
        if (evt.getX() > toleranciaX)
            posX-=avanceX;
        
        if (evt.getY() > toleranciaY) posY-=avanceY;
        if (evt.getY() + toleranciaY < this.getHeight()) posY+=avanceY;
        
        
        if (posX + image.getWidth() <= this.getWidth()) posX = this.getWidth() - image.getWidth();
        if (posX > 0) posX = 0;
        
        if (posY + image.getHeight() <= this.getHeight()) posY = this.getHeight() - image.getHeight();
        if (posY > 0) posY = 0;
        this.paintComponent(this.getGraphics());
    }//GEN-LAST:event_formMouseMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
