/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FAVisualizdor.java
 *
 * Created on 06-nov-2011, 16:18:15
 */
package gui.ventanas;

/**
 *
 * @author Fede
 */
public class FAVisualizdor extends javax.swing.JPanel {

    /** Creates new form FAVisualizdor */
    public FAVisualizdor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expresiones1 = new gui.ventanas.Expresiones();
        fAtable1 = new gui.ventanas.FAtable();
        emulator21 = new gui.ventanas.Emulator2();

        expresiones1.setName("expresiones1"); // NOI18N

        setName("Form"); // NOI18N

        fAtable1.setName("fAtable1"); // NOI18N

        emulator21.setName("emulator21"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fAtable1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
            .addComponent(emulator21, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fAtable1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emulator21, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public gui.ventanas.Emulator2 emulator21;
    private gui.ventanas.Expresiones expresiones1;
    public gui.ventanas.FAtable fAtable1;
    // End of variables declaration//GEN-END:variables
}
