/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on 08-oct-2011, 14:35:01
 */
package gui.ventanas;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Arturo
 */
public class MainWindow extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Calendar clikado;
    int nPestañas = 2;

    /** Creates new form MainWindow */
    public MainWindow() {
        
        initComponents();
        //this.setBorder(null);
        
        
        jTabbedPane1.addTab("Definicion 1", new Automatas());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gui.ventanas.GrafosVentanasApp.class).getContext().getResourceMap(MainWindow.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyReleased(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 972, Short.MAX_VALUE)
            .addGap(0, 972, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGap(0, 512, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        if (clikado == null) {
            clikado = new GregorianCalendar();
        } else {
            GregorianCalendar ahora = new GregorianCalendar();
            Long tiempo = ahora.getTimeInMillis()-  clikado.getTimeInMillis() ;
            //System.out.println("Tiempo entre clicks: " + tiempo); 
            if (tiempo < 200) {
                
                System.out.println("Abriendo pestaña #" + nPestañas);
                jTabbedPane1.addTab("Definicion " + nPestañas, new Automatas());
                
                jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount() - 1);
                nPestañas++;
            }
            clikado = null;
            
        }
}//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyReleased
        //System.out.println(evt.getKeyCode());
        //System.out.println(evt.getModifiers());
        if (evt.getKeyCode() == 87 && evt.getModifiers() == 2)
        {
            //System.out.println(jTabbedPane1.getSelectedIndex());
            if (jTabbedPane1.getSelectedIndex() != 0)
            {
                 System.out.println("Cerrando pestaña #" + jTabbedPane1.getSelectedIndex());
                jTabbedPane1.removeTabAt(jTabbedPane1.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_jTabbedPane1KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
